#!/usr/bin/env python3
"""Draw the generated car, without Unity.

A build cycle is twelve minutes, and until now every question about how
the car looks has cost one — including three spent guessing wrong from a
screenshot. The mesh is generated by arithmetic in
`unity/Packages/com.mumu.f1core/Runtime/CarMesh.cs`, and arithmetic can
be checked here, in a second, with the same lighting model the shader
uses: four hard bands off one directional light, a flat ambient term,
and colour carried per vertex.

It is a reading of that file, not a second copy of it — if the two
disagree, this one is wrong. Its job is to answer "what colour is the
top of the engine cover" without asking a runner.

    python3 tools/preview-car.py out.png [--yaw 200] [--pitch 18]
"""

import math
import os
import re
import struct
import sys
import zlib

LIVERY = (0.80, 0.07, 0.10)
DARK = (0.10, 0.11, 0.13)
CARBON = (0.16, 0.17, 0.20)
TRIM = (0.93, 0.94, 0.96)
GOLD = (0.92, 0.74, 0.16)
VISOR = (0.13, 0.16, 0.22)
RUBBER = (0.09, 0.09, 0.10)
RIM = (0.72, 0.74, 0.78)

tris = []


def tri(a, b, c, col):
    ux, uy, uz = b[0] - a[0], b[1] - a[1], b[2] - a[2]
    vx, vy, vz = c[0] - a[0], c[1] - a[1], c[2] - a[2]
    n = (uy * vz - uz * vy, uz * vx - ux * vz, ux * vy - uy * vx)
    m = math.sqrt(sum(k * k for k in n))
    if m < 1e-12:
        return
    tris.append((a, b, c, tuple(k / m for k in n), col))


def quad(a, b, c, d, col):
    tri(a, b, c, col)
    tri(a, c, d, col)


def box(at, size, col):
    x, y, z = size[0] / 2, size[1] / 2, size[2] / 2

    def P(sx, sy, sz):
        return (at[0] + sx * x, at[1] + sy * y, at[2] + sz * z)

    quad(P(-1, -1, 1), P(1, -1, 1), P(1, 1, 1), P(-1, 1, 1), col)
    quad(P(1, -1, -1), P(-1, -1, -1), P(-1, 1, -1), P(1, 1, -1), col)
    quad(P(1, -1, 1), P(1, -1, -1), P(1, 1, -1), P(1, 1, 1), col)
    quad(P(-1, -1, -1), P(-1, -1, 1), P(-1, 1, 1), P(-1, 1, -1), col)
    quad(P(-1, 1, 1), P(1, 1, 1), P(1, 1, -1), P(-1, 1, -1), col)
    quad(P(-1, -1, -1), P(1, -1, -1), P(1, -1, 1), P(-1, -1, 1), col)


def ball(at, r, sides, rings, col):
    def P(i, j):
        phi = math.pi * j / rings
        th = 2 * math.pi * i / sides
        return (at[0] + r * math.sin(phi) * math.cos(th),
                at[1] + r * math.cos(phi),
                at[2] + r * math.sin(phi) * math.sin(th))

    for j in range(rings):
        for i in range(sides):
            a, b, c, d = P(i, j), P(i + 1, j), P(i + 1, j + 1), P(i, j + 1)
            if j == 0:
                tri(a, c, d, col)
            elif j == rings - 1:
                tri(a, b, c, col)
            else:
                quad(a, b, c, d, col)


SOURCE = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                      '..', 'unity', 'Packages', 'com.mumu.f1core',
                      'Runtime', 'CarMesh.cs')


def hull():
    """The section table, read out of the C# rather than copied.

    The table is the part that gets tuned, so it is the part most likely
    to drift between the model and this. Everything else here — the
    wings, the halo, the floor — is still a hand reading of that file and
    can fall behind it; when it does, this one is wrong.
    """
    text = open(SOURCE, encoding='utf-8').read()
    rows = re.findall(r'new Section\(([-0-9., ]+)\)', text)
    if not rows:
        raise SystemExit(f'no Section rows found in {SOURCE}')
    return [tuple(float(v) for v in r.split(',')) for r in rows]


HULL = hull()

def ring(s):
    z, foot, waist, deck, floor, sh, top = s
    return [(-foot, floor, z), (foot, floor, z), (waist, sh, z),
            (deck, top, z), (-deck, top, z), (-waist, sh, z)]


def cap(r, front, col):
    c = tuple(sum(p[i] for p in r) / len(r) for i in range(3))
    for k in range(len(r)):
        k2 = (k + 1) % len(r)
        if front:
            tri(c, r[k], r[k2], col)
        else:
            tri(c, r[k2], r[k], col)


def build_body(livery):
    prev = ring(HULL[0])
    cap(prev, True, livery)
    for s in HULL[1:]:
        nxt = ring(s)
        for k in range(6):
            k2 = (k + 1) % 6
            quad(prev[k2], prev[k], nxt[k], nxt[k2], livery)
        prev = nxt
    cap(prev, False, livery)

    # Cockpit
    box((0, 0.37, 0.30), (0.40, 0.06, 1.00), DARK)
    box((-0.25, 0.39, 0.05), (0.12, 0.09, 0.52), livery)
    box((0.25, 0.39, 0.05), (0.12, 0.09, 0.52), livery)
    ball((0, 0.45, 0.26), 0.14, 8, 5, TRIM)
    box((0, 0.46, 0.38), (0.19, 0.07, 0.06), VISOR)
    box((0, 0.52, -0.02), (0.26, 0.28, 0.16), CARBON)
    box((0, 0.49, -0.30), (0.23, 0.20, 0.44), livery)

    # Fin
    prof = [(0, 0.56, -0.30), (0, 0.60, -1.55), (0, 0.40, -1.95), (0, 0.40, -1.10)]
    t = 0.012
    for i in range(4):
        a, c = prof[i], prof[(i + 1) % 4]
        quad((-t, a[1], a[2]), (t, a[1], a[2]), (t, c[1], c[2]), (-t, c[1], c[2]), livery)
    quad((t, prof[0][1], prof[0][2]), (t, prof[1][1], prof[1][2]),
         (t, prof[2][1], prof[2][2]), (t, prof[3][1], prof[3][2]), livery)
    quad((-t, prof[3][1], prof[3][2]), (-t, prof[2][1], prof[2][2]),
         (-t, prof[1][1], prof[1][2]), (-t, prof[0][1], prof[0][2]), livery)

    # Halo
    segs, ht = 9, 0.035

    def on(u):
        a = math.pi * (0.06 + 0.88 * u)
        return (-math.cos(a) * 0.42, 0.50 + math.sin(a) * 0.055, 0.28 + math.sin(a) * 0.34)

    def sec4(at, towards, half):
        dx, dz = towards[0] - at[0], towards[2] - at[2]
        L = math.hypot(dx, dz) or 1.0
        dx, dz = dx / L, dz / L
        px, pz = -dz * half, dx * half
        return [(at[0] - px, at[1] - half, at[2] - pz), (at[0] + px, at[1] - half, at[2] + pz),
                (at[0] + px, at[1] + half, at[2] + pz), (at[0] - px, at[1] + half, at[2] - pz)]

    prev = sec4(on(0), on(1.0 / segs), ht)
    for i in range(1, segs + 1):
        here = on(i / segs)
        if i == segs:
            back = on((i - 1) / segs)
            ahead = (2 * here[0] - back[0], 2 * here[1] - back[1], 2 * here[2] - back[2])
        else:
            ahead = on(min(1.0, (i + 1) / segs))
        nxt = sec4(here, ahead, ht)
        for k in range(4):
            quad(prev[(k + 1) % 4], prev[k], nxt[k], nxt[(k + 1) % 4], CARBON)
        prev = nxt
    box((0, 0.45, 0.62), (0.05, 0.18, 0.08), CARBON)

    # Sidepods
    for side in (-1, 1):
        box((side * 0.40, -0.06, 0.50), (0.14, 0.22, 0.12), DARK)
        box((side * 0.38, -0.15, 1.05), (0.04, 0.18, 0.56), CARBON)
        box((side * 0.34, 0.30, -0.35), (0.26, 0.03, 0.36), CARBON)

    # Front wing
    box((0, -0.27, 3.02), (1.88, 0.035, 0.46), CARBON)
    box((0, -0.20, 3.18), (1.74, 0.035, 0.28), livery)
    for side in (-1, 1):
        box((side * 0.94, -0.18, 3.04), (0.04, 0.26, 0.58), TRIM)
        box((side * 0.09, -0.19, 2.88), (0.035, 0.16, 0.28), CARBON)

    # Rear wing
    box((0, 0.61, -2.14), (1.05, 0.045, 0.40), CARBON)
    box((0, 0.52, -2.25), (1.02, 0.035, 0.22), livery)
    box((0, -0.02, -2.18), (0.76, 0.035, 0.24), CARBON)
    for side in (-1, 1):
        box((side * 0.53, 0.42, -2.14), (0.035, 0.44, 0.56), TRIM)
    box((0, -0.14, -2.34), (0.09, 0.09, 0.05), GOLD)
    box((0, 0.40, -2.08), (0.06, 0.38, 0.18), CARBON)

    # Floor
    box((0, -0.25, -0.30), (0.92, 0.03, 2.60), CARBON)
    for i in range(3):
        box((0, -0.24 + i * 0.04, -1.70 - i * 0.22),
            (0.82 - i * 0.06, 0.03, 0.26), DARK)


def tube(at, radius, height, sides, col):
    """A closed cylinder, base at `at`, axis +Y — as MeshBuilder.Tube."""
    def ring_(centre, i):
        th = 2 * math.pi * i / sides
        return (centre[0] + radius * math.cos(th), centre[1],
                centre[2] + radius * math.sin(th))

    lid = (at[0], at[1] + height, at[2])
    for i in range(sides):
        b0, b1 = ring_(at, i), ring_(at, i + 1)
        t0, t1 = ring_(lid, i), ring_(lid, i + 1)
        quad(b0, b1, t1, t0, col)
        tri(at, b1, b0, col)
        tri(lid, t0, t1, col)


def build_wheels():
    """Four of CarMesh.Wheel(), stood on their rims at the hubs.

    The hub is `CarController.HubRest`: the hardpoint at +0.16 less the
    spring's 0.12 rest length, so +0.04, which puts a 0.36 wheel exactly
    on a road at -0.32.
    """
    for (wx, wz) in ((-0.80, 1.98), (0.80, 1.98), (-0.775, -1.62), (0.775, -1.62)):
        # The wheel is generated axis-up and stood on its rim by the view,
        # so here it is written already standing: x is the axle.
        radius, half = 0.36, 0.18
        n = 16
        for i in range(n):
            t0 = 2 * math.pi * i / n
            t1 = 2 * math.pi * (i + 1) / n
            p0 = (0.04 + radius * math.cos(t0), wz + radius * math.sin(t0))
            p1 = (0.04 + radius * math.cos(t1), wz + radius * math.sin(t1))
            quad((wx - half, p0[0], p0[1]), (wx - half, p1[0], p1[1]),
                 (wx + half, p1[0], p1[1]), (wx + half, p0[0], p0[1]), RUBBER)
            # sidewalls, so the tyre is solid rather than a hoop
            tri((wx - half, 0.04, wz), (wx - half, p1[0], p1[1]),
                (wx - half, p0[0], p0[1]), RUBBER)
            tri((wx + half, 0.04, wz), (wx + half, p0[0], p0[1]),
                (wx + half, p1[0], p1[1]), RUBBER)

        for side in (-1, 1):
            x = wx + side * (half + 0.004)
            for sp in range(5):
                a = 2 * math.pi * sp / 5
                dy, dz = math.cos(a), math.sin(a)

                def At(r, t):
                    return (x, 0.04 + dy * r - dz * t, wz + dz * r + dy * t)

                if side > 0:
                    quad(At(0.07, 0.035), At(0.26, 0.035),
                         At(0.26, -0.035), At(0.07, -0.035), RIM)
                else:
                    quad(At(0.07, -0.035), At(0.26, -0.035),
                         At(0.26, 0.035), At(0.07, 0.035), RIM)


# ---- render -----------------------------------------------------------

SUN = (0.353, 0.788, -0.504)
AMBIENT = (0.45, 0.62, 0.80)
BANDS, FLOOR = 4.0, 0.35


def shade(col, n):
    ndl = max(0.0, sum(a * b for a, b in zip(n, SUN)))
    stepped = min(1.0, math.floor(ndl * BANDS) / (BANDS - 1.0))
    s = FLOOR + (1.0 - FLOOR) * stepped
    return tuple(min(1.0, col[i] * s * (1.4, 1.33, 1.21)[i] + col[i] * AMBIENT[i] * 0.5)
                 for i in range(3))


def srgb(v):
    v = max(0.0, min(1.0, v))
    return int(255 * (1.055 * v ** (1 / 2.4) - 0.055 if v > 0.0031308 else 12.92 * v))


def render(path, yaw, pitch, W=900, H=620):
    cy, sy = math.cos(math.radians(yaw)), math.sin(math.radians(yaw))
    cp, sp = math.cos(math.radians(pitch)), math.sin(math.radians(pitch))
    dist, focal = 9.5, 900.0

    def project(p):
        x, y, z = p[0], p[1] - 0.35, p[2]
        x, z = x * cy - z * sy, x * sy + z * cy
        y, z = y * cp - z * sp, y * sp + z * cp
        z += dist
        if z < 0.2:
            return None
        return (W / 2 + focal * x / z, H / 2 - focal * y / z, z)

    depth = [1e9] * (W * H)
    buf = bytearray([28, 32, 38] * (W * H))

    for a, b, c, n, col in tris:
        pa, pb, pc = project(a), project(b), project(c)
        if not (pa and pb and pc):
            continue
        area = (pb[0] - pa[0]) * (pc[1] - pa[1]) - (pb[1] - pa[1]) * (pc[0] - pa[0])
        if area >= 0:
            continue                      # back face
        r, g, bl = (srgb(v) for v in shade(col, n))
        x0 = max(0, int(min(pa[0], pb[0], pc[0])))
        x1 = min(W - 1, int(max(pa[0], pb[0], pc[0])) + 1)
        y0 = max(0, int(min(pa[1], pb[1], pc[1])))
        y1 = min(H - 1, int(max(pa[1], pb[1], pc[1])) + 1)
        for py in range(y0, y1 + 1):
            for px in range(x0, x1 + 1):
                w0 = (pb[0] - pa[0]) * (py + .5 - pa[1]) - (pb[1] - pa[1]) * (px + .5 - pa[0])
                w1 = (pc[0] - pb[0]) * (py + .5 - pb[1]) - (pc[1] - pb[1]) * (px + .5 - pb[0])
                w2 = (pa[0] - pc[0]) * (py + .5 - pc[1]) - (pa[1] - pc[1]) * (px + .5 - pc[0])
                if not (w0 <= 0 and w1 <= 0 and w2 <= 0):
                    continue
                z = (pa[2] + pb[2] + pc[2]) / 3
                i = py * W + px
                if z < depth[i]:
                    depth[i] = z
                    buf[i * 3:i * 3 + 3] = bytes((r, g, bl))

    raw = bytearray()
    for y in range(H):
        raw.append(0)
        raw += buf[y * W * 3:(y + 1) * W * 3]

    def chunk(t, d):
        return struct.pack('>I', len(d)) + t + d + struct.pack('>I', zlib.crc32(t + d) & 0xffffffff)

    png = (b'\x89PNG\r\n\x1a\n'
           + chunk(b'IHDR', struct.pack('>IIBBBBB', W, H, 8, 2, 0, 0, 0))
           + chunk(b'IDAT', zlib.compress(bytes(raw), 6))
           + chunk(b'IEND', b''))
    open(path, 'wb').write(png)


def build_ground():
    """The road, at y = -0.32.

    Here because the whole point of the last revision was ride height, and
    a car floating in a void is exactly the picture that hid it.
    """
    g, r = -0.32, 9.0
    quad((-r, g, r), (r, g, r), (r, g, -r), (-r, g, -r), (0.30, 0.32, 0.35))


if __name__ == '__main__':
    out = sys.argv[1] if len(sys.argv) > 1 else 'car.png'
    yaw = float(sys.argv[sys.argv.index('--yaw') + 1]) if '--yaw' in sys.argv else 205.0
    pitch = float(sys.argv[sys.argv.index('--pitch') + 1]) if '--pitch' in sys.argv else 16.0
    build_ground()
    build_body(LIVERY)
    build_wheels()
    render(out, yaw, pitch)
    print(f'{out}: {len(tris)} triangles, yaw {yaw}, pitch {pitch}')
